export const siteConfig = {
  name: "Dennis Waweru",
  title: "Dennis Kinuthia",
  role: "Full Stack TypeScript Developer",
  description:
    "Crafting exceptional web experiences with full-stack TypeScript. Based in Nairobi, Kenya.",
  navItems: [
    { label: "About", href: "#about" },
    { label: "Skills", href: "#skills" },
    { label: "Projects", href: "#projects" },
    { label: "Articles", href: "#articles" },
    { label: "Journal", href: "#journal" },
    { label: "Contact", href: "#contact" },
  ],
  links: {
    github: "https://github.com/tigawanna",
    linkedin: "https://linkedin.com/in/dennis-kinuthia-waweru",
    devto: "https://dev.to/tigawanna",
    email: "denniskinuthiawaweru@gmail.com",
    emailTo: "mailto:denniskinuthiawaweru@gmail.com",
    twitter: "https://twitter.com/tigawanna",
    website: "https://tigawanna-portfolio.vercel.app",
  },
  techSkills: [
    "React & Next.js",
    "TypeScript",
    "TanStack Start",
    "GraphQL",
    "Node.js",
    "Tailwind CSS",
    "React Native",
    "REST APIs",
    "Prisma & Drizzle",
    "Authentication",
    "State Management",
    "Testing",
    "CI/CD",
    "Performance",
    "Accessibility",
  ],
  assets: {
    favicon: "/favicon.ico",
    appleTouchIcon: "/apple-touch-icon.png",
    icon: "/icon.png",
    ogImage: "/opengraph-image.jpg",
    ogImageAlt: "image of dennis kinuthia, a fullstack software developer",
  },
} as const;
