export {
  howIWorkCards,
  howIWorkSections,
  howIWorkSummary,
  infoDietSources,
  siteSeoDescription,
  siteSeoKeywords,
  siteSeoOgImageAlt,
  siteSeoTitle,
  stackCubeFaces,
  techChoices,
  type InfoCard,
  type InfoDietSource,
  type InfoDietSourceKind,
  type StackCubeFace,
} from "@repo/site-constants";
