// export const pkgTypesArr = [
//     "React+Vite",
//     "React+Relay",
//     "React-native",
//     "Rakkasjs",
//     "Nextjs",
//     "Remix",
//     "redwood",
//     "Astro",
//     "Solidjs",
//     "Qwik",
//     "Svelte",
//     "Nuxt",
//     "Vue",
//     "Nodejs",
//     "Deno",
//     "Bun",
//     "Others",
// ] as const;

export const pkgTypesArr = [
  { name: "React+Vite", image: "/frameworks/vite.svg" },
  { name: "React+Relay", image: "/frameworks/relay.webp" },
  { name: "React-native", image: "/frameworks//react.png" },
  { name: "Rakkasjs", image: "/frameworks/rakkas.png" },
  { name: "Nextjs", image: "/frameworks/next.png" },
  { name: "Remix", image: "/frameworks/remix.jpg" },
  { name: "redwood", image: "/frameworks/redwood.png" },
  { name: "Astro", image: "/frameworks/astro.jpeg" },
  { name: "Solidjs", image: "/frameworks/solid.jpg" },
  { name: "Qwik", image: "/frameworks/qwik.png" },
  { name: "Svelte", image: "/frameworks/svelte.png" },
  { name: "Nodejs", image: "/frameworks/node.png" },
  { name: "Deno", image: "/frameworks/deno.png" },
  { name: "Bun", image: "/frameworks/bun.png" },
  { name: "Others", image: "/frameworks/ts.png" },
] as const;
