/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OgRouteImport } from './routes/og'
import { Route as GgRouteImport } from './routes/gg'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonsIndexRouteImport } from './routes/lessons/index'
import { Route as CreatureFeatureIndexRouteImport } from './routes/creature-feature/index'
import { Route as ProjectNameRouteImport } from './routes/project/$name'
import { Route as LessonsLessonIdRouteImport } from './routes/lessons/$lessonId'

const OgRoute = OgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => rootRouteImport,
} as any)
const GgRoute = GgRouteImport.update({
  id: '/gg',
  path: '/gg',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatureFeatureIndexRoute = CreatureFeatureIndexRouteImport.update({
  id: '/creature-feature/',
  path: '/creature-feature/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectNameRoute = ProjectNameRouteImport.update({
  id: '/project/$name',
  path: '/project/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsLessonIdRoute = LessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gg': typeof GgRoute
  '/og': typeof OgRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/project/$name': typeof ProjectNameRoute
  '/creature-feature/': typeof CreatureFeatureIndexRoute
  '/lessons/': typeof LessonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gg': typeof GgRoute
  '/og': typeof OgRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/project/$name': typeof ProjectNameRoute
  '/creature-feature': typeof CreatureFeatureIndexRoute
  '/lessons': typeof LessonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gg': typeof GgRoute
  '/og': typeof OgRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/project/$name': typeof ProjectNameRoute
  '/creature-feature/': typeof CreatureFeatureIndexRoute
  '/lessons/': typeof LessonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gg'
    | '/og'
    | '/lessons/$lessonId'
    | '/project/$name'
    | '/creature-feature/'
    | '/lessons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gg'
    | '/og'
    | '/lessons/$lessonId'
    | '/project/$name'
    | '/creature-feature'
    | '/lessons'
  id:
    | '__root__'
    | '/'
    | '/gg'
    | '/og'
    | '/lessons/$lessonId'
    | '/project/$name'
    | '/creature-feature/'
    | '/lessons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GgRoute: typeof GgRoute
  OgRoute: typeof OgRoute
  LessonsLessonIdRoute: typeof LessonsLessonIdRoute
  ProjectNameRoute: typeof ProjectNameRoute
  CreatureFeatureIndexRoute: typeof CreatureFeatureIndexRoute
  LessonsIndexRoute: typeof LessonsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/og': {
      id: '/og'
      path: '/og'
      fullPath: '/og'
      preLoaderRoute: typeof OgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gg': {
      id: '/gg'
      path: '/gg'
      fullPath: '/gg'
      preLoaderRoute: typeof GgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creature-feature/': {
      id: '/creature-feature/'
      path: '/creature-feature'
      fullPath: '/creature-feature/'
      preLoaderRoute: typeof CreatureFeatureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$name': {
      id: '/project/$name'
      path: '/project/$name'
      fullPath: '/project/$name'
      preLoaderRoute: typeof ProjectNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$lessonId': {
      id: '/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof LessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GgRoute: GgRoute,
  OgRoute: OgRoute,
  LessonsLessonIdRoute: LessonsLessonIdRoute,
  ProjectNameRoute: ProjectNameRoute,
  CreatureFeatureIndexRoute: CreatureFeatureIndexRoute,
  LessonsIndexRoute: LessonsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
