export const queryKeyPrefixes = {
  viewer: "viewer",
  users: "users",
  organizations: "organizations",
  invitations: "invitations",
  kitchenProfile: "kitchenProfile",
  cuisineTypes: "cuisineTypes",
  deviceSessions: "deviceSessions",
  lessons: "lessons",
  github: "github",
  backstage: "backstage",
  openrouter: "openrouter",
  canvas: "canvas",
  canvasDemoItems: "canvasDemoItems",
  "canvas-demo-items": "canvas-demo-items",
} as const;
