/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OgRouteImport } from './routes/og'
import { Route as CanvasLayoutRouteImport } from './routes/canvas/layout'
import { Route as BackstageLayoutRouteImport } from './routes/_backstage/layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonsIndexRouteImport } from './routes/lessons/index'
import { Route as CreatureFeatureIndexRouteImport } from './routes/creature-feature/index'
import { Route as CanvasIndexRouteImport } from './routes/canvas/index'
import { Route as ProjectNameRouteImport } from './routes/project/$name'
import { Route as LessonsLessonIdRouteImport } from './routes/lessons/$lessonId'
import { Route as BackstageSignInRouteImport } from './routes/backstage/sign-in'
import { Route as CanvasColorIndexRouteImport } from './routes/canvas/$color/index'
import { Route as BackstageBackstageIndexRouteImport } from './routes/_backstage/backstage/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as BackstageBackstageReposRouteImport } from './routes/_backstage/backstage/repos'
import { Route as BackstageBackstageMessagesRouteImport } from './routes/_backstage/backstage/messages'
import { Route as BackstageBackstageJournalRouteImport } from './routes/_backstage/backstage/journal'
import { Route as BackstageBackstageProjectsIndexRouteImport } from './routes/_backstage/backstage/projects/index'
import { Route as BackstageBackstageProjectsOwnerIndexRouteImport } from './routes/_backstage/backstage/projects/$owner/index'
import { Route as BackstageBackstageProjectsOwnerRepoIndexRouteImport } from './routes/_backstage/backstage/projects/$owner/$repo/index'

const OgRoute = OgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasLayoutRoute = CanvasLayoutRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const BackstageLayoutRoute = BackstageLayoutRouteImport.update({
  id: '/_backstage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatureFeatureIndexRoute = CreatureFeatureIndexRouteImport.update({
  id: '/creature-feature/',
  path: '/creature-feature/',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasIndexRoute = CanvasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CanvasLayoutRoute,
} as any)
const ProjectNameRoute = ProjectNameRouteImport.update({
  id: '/project/$name',
  path: '/project/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsLessonIdRoute = LessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const BackstageSignInRoute = BackstageSignInRouteImport.update({
  id: '/backstage/sign-in',
  path: '/backstage/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasColorIndexRoute = CanvasColorIndexRouteImport.update({
  id: '/$color/',
  path: '/$color/',
  getParentRoute: () => CanvasLayoutRoute,
} as any)
const BackstageBackstageIndexRoute = BackstageBackstageIndexRouteImport.update({
  id: '/backstage/',
  path: '/backstage/',
  getParentRoute: () => BackstageLayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BackstageBackstageReposRoute = BackstageBackstageReposRouteImport.update({
  id: '/backstage/repos',
  path: '/backstage/repos',
  getParentRoute: () => BackstageLayoutRoute,
} as any)
const BackstageBackstageMessagesRoute =
  BackstageBackstageMessagesRouteImport.update({
    id: '/backstage/messages',
    path: '/backstage/messages',
    getParentRoute: () => BackstageLayoutRoute,
  } as any)
const BackstageBackstageJournalRoute =
  BackstageBackstageJournalRouteImport.update({
    id: '/backstage/journal',
    path: '/backstage/journal',
    getParentRoute: () => BackstageLayoutRoute,
  } as any)
const BackstageBackstageProjectsIndexRoute =
  BackstageBackstageProjectsIndexRouteImport.update({
    id: '/backstage/projects/',
    path: '/backstage/projects/',
    getParentRoute: () => BackstageLayoutRoute,
  } as any)
const BackstageBackstageProjectsOwnerIndexRoute =
  BackstageBackstageProjectsOwnerIndexRouteImport.update({
    id: '/backstage/projects/$owner/',
    path: '/backstage/projects/$owner/',
    getParentRoute: () => BackstageLayoutRoute,
  } as any)
const BackstageBackstageProjectsOwnerRepoIndexRoute =
  BackstageBackstageProjectsOwnerRepoIndexRouteImport.update({
    id: '/backstage/projects/$owner/$repo/',
    path: '/backstage/projects/$owner/$repo/',
    getParentRoute: () => BackstageLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/canvas': typeof CanvasLayoutRouteWithChildren
  '/og': typeof OgRoute
  '/backstage/sign-in': typeof BackstageSignInRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/project/$name': typeof ProjectNameRoute
  '/canvas/': typeof CanvasIndexRoute
  '/creature-feature/': typeof CreatureFeatureIndexRoute
  '/lessons/': typeof LessonsIndexRoute
  '/backstage/journal': typeof BackstageBackstageJournalRoute
  '/backstage/messages': typeof BackstageBackstageMessagesRoute
  '/backstage/repos': typeof BackstageBackstageReposRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/backstage/': typeof BackstageBackstageIndexRoute
  '/canvas/$color/': typeof CanvasColorIndexRoute
  '/backstage/projects/': typeof BackstageBackstageProjectsIndexRoute
  '/backstage/projects/$owner/': typeof BackstageBackstageProjectsOwnerIndexRoute
  '/backstage/projects/$owner/$repo/': typeof BackstageBackstageProjectsOwnerRepoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/og': typeof OgRoute
  '/backstage/sign-in': typeof BackstageSignInRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/project/$name': typeof ProjectNameRoute
  '/canvas': typeof CanvasIndexRoute
  '/creature-feature': typeof CreatureFeatureIndexRoute
  '/lessons': typeof LessonsIndexRoute
  '/backstage/journal': typeof BackstageBackstageJournalRoute
  '/backstage/messages': typeof BackstageBackstageMessagesRoute
  '/backstage/repos': typeof BackstageBackstageReposRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/backstage': typeof BackstageBackstageIndexRoute
  '/canvas/$color': typeof CanvasColorIndexRoute
  '/backstage/projects': typeof BackstageBackstageProjectsIndexRoute
  '/backstage/projects/$owner': typeof BackstageBackstageProjectsOwnerIndexRoute
  '/backstage/projects/$owner/$repo': typeof BackstageBackstageProjectsOwnerRepoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_backstage': typeof BackstageLayoutRouteWithChildren
  '/canvas': typeof CanvasLayoutRouteWithChildren
  '/og': typeof OgRoute
  '/backstage/sign-in': typeof BackstageSignInRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/project/$name': typeof ProjectNameRoute
  '/canvas/': typeof CanvasIndexRoute
  '/creature-feature/': typeof CreatureFeatureIndexRoute
  '/lessons/': typeof LessonsIndexRoute
  '/_backstage/backstage/journal': typeof BackstageBackstageJournalRoute
  '/_backstage/backstage/messages': typeof BackstageBackstageMessagesRoute
  '/_backstage/backstage/repos': typeof BackstageBackstageReposRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_backstage/backstage/': typeof BackstageBackstageIndexRoute
  '/canvas/$color/': typeof CanvasColorIndexRoute
  '/_backstage/backstage/projects/': typeof BackstageBackstageProjectsIndexRoute
  '/_backstage/backstage/projects/$owner/': typeof BackstageBackstageProjectsOwnerIndexRoute
  '/_backstage/backstage/projects/$owner/$repo/': typeof BackstageBackstageProjectsOwnerRepoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/canvas'
    | '/og'
    | '/backstage/sign-in'
    | '/lessons/$lessonId'
    | '/project/$name'
    | '/canvas/'
    | '/creature-feature/'
    | '/lessons/'
    | '/backstage/journal'
    | '/backstage/messages'
    | '/backstage/repos'
    | '/api/auth/$'
    | '/backstage/'
    | '/canvas/$color/'
    | '/backstage/projects/'
    | '/backstage/projects/$owner/'
    | '/backstage/projects/$owner/$repo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/og'
    | '/backstage/sign-in'
    | '/lessons/$lessonId'
    | '/project/$name'
    | '/canvas'
    | '/creature-feature'
    | '/lessons'
    | '/backstage/journal'
    | '/backstage/messages'
    | '/backstage/repos'
    | '/api/auth/$'
    | '/backstage'
    | '/canvas/$color'
    | '/backstage/projects'
    | '/backstage/projects/$owner'
    | '/backstage/projects/$owner/$repo'
  id:
    | '__root__'
    | '/'
    | '/_backstage'
    | '/canvas'
    | '/og'
    | '/backstage/sign-in'
    | '/lessons/$lessonId'
    | '/project/$name'
    | '/canvas/'
    | '/creature-feature/'
    | '/lessons/'
    | '/_backstage/backstage/journal'
    | '/_backstage/backstage/messages'
    | '/_backstage/backstage/repos'
    | '/api/auth/$'
    | '/_backstage/backstage/'
    | '/canvas/$color/'
    | '/_backstage/backstage/projects/'
    | '/_backstage/backstage/projects/$owner/'
    | '/_backstage/backstage/projects/$owner/$repo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackstageLayoutRoute: typeof BackstageLayoutRouteWithChildren
  CanvasLayoutRoute: typeof CanvasLayoutRouteWithChildren
  OgRoute: typeof OgRoute
  BackstageSignInRoute: typeof BackstageSignInRoute
  LessonsLessonIdRoute: typeof LessonsLessonIdRoute
  ProjectNameRoute: typeof ProjectNameRoute
  CreatureFeatureIndexRoute: typeof CreatureFeatureIndexRoute
  LessonsIndexRoute: typeof LessonsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/og': {
      id: '/og'
      path: '/og'
      fullPath: '/og'
      preLoaderRoute: typeof OgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_backstage': {
      id: '/_backstage'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BackstageLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creature-feature/': {
      id: '/creature-feature/'
      path: '/creature-feature'
      fullPath: '/creature-feature/'
      preLoaderRoute: typeof CreatureFeatureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas/': {
      id: '/canvas/'
      path: '/'
      fullPath: '/canvas/'
      preLoaderRoute: typeof CanvasIndexRouteImport
      parentRoute: typeof CanvasLayoutRoute
    }
    '/project/$name': {
      id: '/project/$name'
      path: '/project/$name'
      fullPath: '/project/$name'
      preLoaderRoute: typeof ProjectNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$lessonId': {
      id: '/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof LessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backstage/sign-in': {
      id: '/backstage/sign-in'
      path: '/backstage/sign-in'
      fullPath: '/backstage/sign-in'
      preLoaderRoute: typeof BackstageSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas/$color/': {
      id: '/canvas/$color/'
      path: '/$color'
      fullPath: '/canvas/$color/'
      preLoaderRoute: typeof CanvasColorIndexRouteImport
      parentRoute: typeof CanvasLayoutRoute
    }
    '/_backstage/backstage/': {
      id: '/_backstage/backstage/'
      path: '/backstage'
      fullPath: '/backstage/'
      preLoaderRoute: typeof BackstageBackstageIndexRouteImport
      parentRoute: typeof BackstageLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_backstage/backstage/repos': {
      id: '/_backstage/backstage/repos'
      path: '/backstage/repos'
      fullPath: '/backstage/repos'
      preLoaderRoute: typeof BackstageBackstageReposRouteImport
      parentRoute: typeof BackstageLayoutRoute
    }
    '/_backstage/backstage/messages': {
      id: '/_backstage/backstage/messages'
      path: '/backstage/messages'
      fullPath: '/backstage/messages'
      preLoaderRoute: typeof BackstageBackstageMessagesRouteImport
      parentRoute: typeof BackstageLayoutRoute
    }
    '/_backstage/backstage/journal': {
      id: '/_backstage/backstage/journal'
      path: '/backstage/journal'
      fullPath: '/backstage/journal'
      preLoaderRoute: typeof BackstageBackstageJournalRouteImport
      parentRoute: typeof BackstageLayoutRoute
    }
    '/_backstage/backstage/projects/': {
      id: '/_backstage/backstage/projects/'
      path: '/backstage/projects'
      fullPath: '/backstage/projects/'
      preLoaderRoute: typeof BackstageBackstageProjectsIndexRouteImport
      parentRoute: typeof BackstageLayoutRoute
    }
    '/_backstage/backstage/projects/$owner/': {
      id: '/_backstage/backstage/projects/$owner/'
      path: '/backstage/projects/$owner'
      fullPath: '/backstage/projects/$owner/'
      preLoaderRoute: typeof BackstageBackstageProjectsOwnerIndexRouteImport
      parentRoute: typeof BackstageLayoutRoute
    }
    '/_backstage/backstage/projects/$owner/$repo/': {
      id: '/_backstage/backstage/projects/$owner/$repo/'
      path: '/backstage/projects/$owner/$repo'
      fullPath: '/backstage/projects/$owner/$repo/'
      preLoaderRoute: typeof BackstageBackstageProjectsOwnerRepoIndexRouteImport
      parentRoute: typeof BackstageLayoutRoute
    }
  }
}

interface BackstageLayoutRouteChildren {
  BackstageBackstageJournalRoute: typeof BackstageBackstageJournalRoute
  BackstageBackstageMessagesRoute: typeof BackstageBackstageMessagesRoute
  BackstageBackstageReposRoute: typeof BackstageBackstageReposRoute
  BackstageBackstageIndexRoute: typeof BackstageBackstageIndexRoute
  BackstageBackstageProjectsIndexRoute: typeof BackstageBackstageProjectsIndexRoute
  BackstageBackstageProjectsOwnerIndexRoute: typeof BackstageBackstageProjectsOwnerIndexRoute
  BackstageBackstageProjectsOwnerRepoIndexRoute: typeof BackstageBackstageProjectsOwnerRepoIndexRoute
}

const BackstageLayoutRouteChildren: BackstageLayoutRouteChildren = {
  BackstageBackstageJournalRoute: BackstageBackstageJournalRoute,
  BackstageBackstageMessagesRoute: BackstageBackstageMessagesRoute,
  BackstageBackstageReposRoute: BackstageBackstageReposRoute,
  BackstageBackstageIndexRoute: BackstageBackstageIndexRoute,
  BackstageBackstageProjectsIndexRoute: BackstageBackstageProjectsIndexRoute,
  BackstageBackstageProjectsOwnerIndexRoute:
    BackstageBackstageProjectsOwnerIndexRoute,
  BackstageBackstageProjectsOwnerRepoIndexRoute:
    BackstageBackstageProjectsOwnerRepoIndexRoute,
}

const BackstageLayoutRouteWithChildren = BackstageLayoutRoute._addFileChildren(
  BackstageLayoutRouteChildren,
)

interface CanvasLayoutRouteChildren {
  CanvasIndexRoute: typeof CanvasIndexRoute
  CanvasColorIndexRoute: typeof CanvasColorIndexRoute
}

const CanvasLayoutRouteChildren: CanvasLayoutRouteChildren = {
  CanvasIndexRoute: CanvasIndexRoute,
  CanvasColorIndexRoute: CanvasColorIndexRoute,
}

const CanvasLayoutRouteWithChildren = CanvasLayoutRoute._addFileChildren(
  CanvasLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackstageLayoutRoute: BackstageLayoutRouteWithChildren,
  CanvasLayoutRoute: CanvasLayoutRouteWithChildren,
  OgRoute: OgRoute,
  BackstageSignInRoute: BackstageSignInRoute,
  LessonsLessonIdRoute: LessonsLessonIdRoute,
  ProjectNameRoute: ProjectNameRoute,
  CreatureFeatureIndexRoute: CreatureFeatureIndexRoute,
  LessonsIndexRoute: LessonsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
