import {
  SiApollographql,
  SiCloudflare,
  SiDeno,
  SiExpo,
  SiExpress,
  SiFastify,
  SiFirebase,
  SiGraphql,
  SiMongodb,
  SiNestjs,
  SiNodedotjs,
  SiPocketbase,
  SiPostgresql,
  SiPrisma,
  SiReact,
  SiReactquery,
  SiSqlite,
  SiSupabase,
  SiTailwindcss,
  SiTypescript,
  SiVite,
} from "react-icons/si";

export const TechIcons = [
  { name: "Vite", icon: SiVite },
  { name: "React", icon: SiReact },
  { name: "Expo", icon: SiExpo },
  { name: "Node", icon: SiNodedotjs },
  { name: "TypeScript", icon: SiTypescript },
  { name: "NestJS", icon: SiNestjs },
  { name: "Tailwind", icon: SiTailwindcss },
  { name: "Express", icon: SiExpress },
  { name: "Fastify", icon: SiFastify },
  { name: "GraphQL", icon: SiGraphql },
  { name: "Apollo", icon: SiApollographql },
  { name: "React Query", icon: SiReactquery },
  { name: "Deno", icon: SiDeno },
  { name: "SQLite", icon: SiSqlite },
  { name: "PostgreSQL", icon: SiPostgresql },
  { name: "MongoDB", icon: SiMongodb },
  { name: "Firebase", icon: SiFirebase },
  { name: "Supabase", icon: SiSupabase },
  { name: "Pocketbase", icon: SiPocketbase },
  { name: "Prisma", icon: SiPrisma},
  { name: "Cloudflare", icon: SiCloudflare},
];
